# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never --line-numbers

os:
  editPreset: "nvim-remote"

customCommands:
  - key: "I"
    command: "bun ~/.config/git-ai/index.ts"
    context: "global"
    description: "Create PR with AI-generated description"

gui:
  border: rounded
  showIcons: true
  theme:
    activeBorderColor:
      - "#5ef1ff"
    inactiveBorderColor:
      - "#7b8496"
    searchingActiveBorderColor:
      - "#ff5ef1"
    optionsTextColor:
      - "#3c4048"
    selectedLineBgColor:
      - "#3c4048"
    cherryPickedCommitBgColor:
      - "#3c4048"
    cherryPickedCommitFgColor:
      - "#ff5ea0"
    unstagedChangesColor:
      - "#ffbd5e"
    defaultFgColor:
      - "#ffffff"
